# variables and constants

# constants
WIDTH = 10                                      # vertical grid size
HEIGHT = 30                                     # horizontal grid size
NUM_SAND_PITS = 3                               # random terminal states 
EPSILON = 0.1                                   # the rate at which we explore
ALPHA = 0.1    
GAMMA = 1   

RED   = "\033[1;31m"  
CYAN  = "\033[1;36m"
GREEN = "\033[0;32m"
BLACK  = "\033[0;0m"

# testing
iterations = [1, 100, 1000, 2500, 5000, 10000, 25000, 50000]

# environment
terrain = ['O', 'R', 'G', 'H', 'P']             # different types of terrain on the course. 
                                                # 'OUT', 'ROUGH', 'GREEN', 'HOLE', '(Sand) Pits'
# actions
PUTT = 2                                        # strength 2
DRIVER = 3                                      # strength 3
strengths = [PUTT, DRIVER]
directions = [(-1,0), (1, 0), (0, -1), (0, 1)]  # up, down, left, right
n_actions = len(directions) * 2                 # possible directions * possible powers

# data structures
S = []
S_t = []
Q = dict()
Map = dict()
# ** these are generated by the generate_course method. here is an example of how to call it though.
# S, S_t, Q, Map  = generate_course(WIDTH, HEIGHT, n_actions, NUM_SAND_PITS)